export const ORANGE = '#F04B23';
export const LINKEDIN = 'https://www.linkedin.com/in/jandre-scholtz';
export const services = [
  {name:'Fractional Head of Growth & Performance', label:'Embedded leadership', tag:'PRIMARY ENGAGEMENT', intro:'Senior ownership. Not another layer of advice.', text:'I work inside your business to connect commercial targets with the strategy, acquisition, measurement and people needed to achieve them.', points:['Market strategy, launch and scale','Budget allocation and performance management','Measurement, experimentation and creative','Team, agency and AI-enabled operations'], fit:'For businesses that need someone to own the complete growth system.', timing:'Typically 1–2 days per week · Initial 90-day mandate'},
  {name:'Growth Diagnostic and 90-Day Plan', label:'Diagnose & prioritise', tag:'A CLEAR STARTING POINT', intro:'Find the constraint. Focus the next 90 days.', text:'An independent assessment of your acquisition performance, customer economics, channels, measurement and operating capabilities.', points:['Growth and acquisition baseline','Market, channel and funnel diagnosis','Measurement and attribution gaps','Prioritised experiments and a 30/60/90-day plan'], fit:'For teams preparing to launch, scale investment or improve efficiency.', timing:'Focused assessment · Prioritised action plan'},
  {name:'Performance Transformation Sprint', label:'Solve a defined challenge', tag:'FOCUSED EXECUTION', intro:'One important problem. Structured execution.', text:'A defined project to address the performance challenge holding your team back, from paid acquisition and measurement to experimentation and creative testing.', points:['A clearly defined performance mandate','Senior strategy and project leadership','Hands-on coordination with your specialists','Systems that support your next stage of growth'], fit:'For teams with a known problem that needs senior attention.', timing:'Fixed-term engagement · Four to eight weeks'},
  {name:'Strategic Advisory', label:'An independent perspective', tag:'EXECUTIVE SUPPORT', intro:'A senior sounding board for high-stakes decisions.', text:'Regular strategic challenge for founders, CMOs and growth leaders who own execution but want an experienced, independent perspective.', points:['Strategy reviews and performance analysis','Investment and budget decisions','Agency evaluation and recruitment','Preparation for major growth initiatives'], fit:'For executives who need guidance without embedded leadership.', timing:'Ongoing advisory · Scope tailored to your business'},
  {name:'AI-Enabled Growth Operations Audit', label:'Better systems, less busywork', tag:'PRACTICAL AI', intro:'Start with the bottleneck. Not the technology.', text:'Identify where AI and automation can improve reporting, monitoring, project workflows and decision-making, without adding unnecessary software.', points:['Workflow and bottleneck map','Prioritised AI opportunity map','Build, buy or leave alone recommendations','Implementation roadmap and optional prototype'], fit:'For growth teams seeking practical systems rather than generic AI workshops.', timing:'Workflow-led assessment · Optional prototype'}
];
export const results = [
 {value:'1M', unit:'users in nine months', category:'APP LAUNCH', detail:'Led the growth workstream, as part of a cross-functional team, for a consumer app launch across five international markets. The app reached one million users within its first nine months.', foot:'Five international markets'},
 {value:'$1M', unit:'monthly media spend managed', category:'ACQUISITION AT SCALE', detail:'Led multi-channel acquisition across paid search, paid social and programmatic, with responsibility for strategy, budget allocation, performance targets, measurement and team execution.', foot:'Search · Social · Programmatic'},
 {value:'40%', unit:'reduction in cost per lead', category:'PERFORMANCE EFFICIENCY', detail:'Led the performance strategy and project team for a major client, combining campaign optimisation with broader changes to the acquisition approach.', foot:'Strategy + execution'},
 {value:'20%', unit:'reduction in acquisition cost', category:'SAAS GROWTH', detail:'Managed growth marketing for a SaaS portfolio and improved acquisition efficiency for its largest portfolio company.', foot:'Portfolio growth marketing'},
 {value:'90%', unit:'revenue growth in four months', category:'COMMERCIAL GROWTH', detail:'Developed and executed the growth strategy for a client account, scaling revenue through improved paid-media execution, testing and commercial focus.', foot:'Paid media + experimentation'},
 {value:'1,000+', unit:'subscribers in the first year', category:'SUBSCRIPTION LAUNCH', detail:'Led growth for the launch of a home-internet subscription business, acquiring more than 1,000 subscribers within the first year despite a constrained launch budget.', foot:'Constrained launch budget'}
];
export const faqs = [
 ['How is this different from hiring an agency?', 'An agency typically delivers a defined set of services from outside your organisation. I work inside your business as part of the leadership structure, setting direction, coordinating your team and agencies, and holding the complete growth system accountable. I do not replace every specialist required for execution.'],
 ['Will you work with our existing team?', 'Yes. Most engagements involve an existing internal team, agency or specialist network. My role is to clarify ownership, connect their work and ensure everyone is working toward the same commercial objectives.'],
 ['Are you strategic or hands-on?', 'Both. I work at executive level while staying close to the channels, data and workflows. The balance depends on the mandate, with the greatest value in leadership, diagnosis, decision-making and coordinating execution.'],
 ['How long does an engagement last?', 'Most fractional engagements begin with an initial 90-day mandate, typically one or two days per week. We can then continue, adjust involvement or transition ownership to an internal leader. Defined transformation sprints run for four to eight weeks.'],
 ['Do you work internationally?', 'Yes. I am based in Cape Town and work remotely with businesses across global markets, with strong working-hour overlap with the UK, Europe, the Middle East and parts of North America.'],
 ['Do we need new AI tools?', 'Usually not. I start with the process and assess whether your existing tools can work harder. The recommendation may be to build, buy, improve a workflow or leave it alone. For substantial engineering, security review or deep integrations, I work with appropriate technical specialists.']
];
