"use client";

import { useState, type KeyboardEvent } from 'react';
import { ArrowUpRight, ArrowRight, Plus, Minus, Menu, X, Globe, Check } from 'lucide-react';
import { ORANGE, LINKEDIN, services, results, faqs } from '@/lib/content';
import GrowthSculpture from './growth-sculpture';

export default function Site(){
 const [service,setService]=useState(0); const [openResults,setOpenResults]=useState<number[]>([]); const [faq,setFaq]=useState<number|null>(0); const [menu,setMenu]=useState(false);
 const go=(id:string)=>{document.getElementById('js-'+id)?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});setMenu(false)};
 const active=services[service];
 const navigateTab = (event: KeyboardEvent<HTMLButtonElement>, index: number) => {
   let next = index;
   if (event.key === 'ArrowRight' || event.key === 'ArrowDown') next = (index + 1) % services.length;
   else if (event.key === 'ArrowLeft' || event.key === 'ArrowUp') next = (index - 1 + services.length) % services.length;
   else if (event.key === 'Home') next = 0;
   else if (event.key === 'End') next = services.length - 1;
   else return;
   event.preventDefault();
   setService(next);
   document.getElementById('service-tab-' + next)?.focus();
 };
 return <div className="js-site" id="js-top">
 <a className="skip-link" href="#main-content">Skip to content</a><header className="js-wrap" onKeyDown={(event)=>{if(event.key==='Escape'){setMenu(false);document.querySelector<HTMLButtonElement>('.js-menu')?.focus();}}}><nav className="js-nav" aria-label="Main navigation"><button className="js-textlink" onClick={()=>go('top')} aria-label="Jandré Scholtz home"><span className="js-wordmark"><span className="js-monogram">js.</span>Jandré Scholtz<span style={{color:ORANGE}}>.</span></span></button><div className="js-navlinks"><button onClick={()=>go('results')}>Selected results</button><button onClick={()=>go('services')}>How I help</button><button onClick={()=>go('about')}>About</button><button className="js-contactlink" onClick={()=>go('contact')}>Let’s talk <ArrowUpRight size={15}/></button></div><button className="js-menu" aria-label={menu?'Close menu':'Open menu'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X size={23}/>:<Menu size={23}/>}</button></nav>{menu&&<div className="js-mobile">{[['results','Results'],['services','Services'],['about','About'],['contact','Let’s talk']].map(([id,label])=><button key={id} onClick={()=>go(id)}>{label}</button>)}</div>}</header>
 <main id="main-content" tabIndex={-1}><section className="js-wrap js-hero js-reveal"><div className="js-hero-layout"><div><div className="js-eyebrow"><span className="js-dot"/>Fractional Head of Growth & Performance</div><h1>Senior growth<br/>leadership.<br/><span className="js-serif">Not a full-time<br/>hire.</span></h1><p className="js-hero-copy">I help ambitious digital businesses launch, scale and make customer acquisition more efficient. Clear strategy. Hands-on ownership. Systems that last.</p><div className="js-actions"><button className="js-primary" onClick={()=>go('contact')}>Discuss your growth challenge <ArrowUpRight size={17}/></button><button className="js-textlink" onClick={()=>go('results')}>See the results <ArrowRight size={15}/></button></div></div><GrowthSculpture/></div><div className="js-industries"><span>BUILT FOR DIGITAL BUSINESSES</span><div className="js-industries-list">{['Apps','Fintech','SaaS','Subscriptions','E-commerce'].map(x=><span key={x}>{x}</span>)}</div></div></section>
 <section className="js-wrap js-section" id="js-results"><div className="js-section-head"><div><div className="js-eyebrow">01 / Selected results</div><h2>Less talk.<br/><span className="js-serif">More commercial impact.</span></h2></div><p className="js-side-note">Experience launching, scaling and improving growth across global markets.<br/><span style={{fontSize:10}}>Select a result for the context behind it.</span></p></div><div className="js-results">{results.map((r,i)=><button key={r.category} className={'js-result '+(openResults.includes(i)?'is-open':'')} aria-expanded={openResults.includes(i)} aria-controls={'result-detail-'+i} onClick={()=>setOpenResults(v=>v.includes(i)?v.filter(x=>x!==i):[...v,i])}><span className="js-result-top">{r.category}{openResults.includes(i)?<Minus size={15}/>:<Plus size={15}/>}</span><span className="js-result-value">{r.value}<span style={{color:ORANGE,fontSize:34,letterSpacing:0}}>.</span></span><span className="js-result-unit">{r.unit}</span><span hidden={!openResults.includes(i)} id={'result-detail-'+i} className="js-result-detail">{r.detail}</span><span className="js-result-foot">{r.foot}</span></button>)}</div></section>
 <section className="js-wrap js-section"><div className="js-thesis"><div className="js-eyebrow"><span className="js-dot"/>The missing layer</div><div><h2>You don’t need more activity.<br/>You need someone to<br/><span className="js-serif">own the growth system.</span></h2><p>Growth rarely breaks inside a single ad platform. It breaks between strategy, customer economics, creative, measurement and execution. I connect those pieces, giving your team clear priorities and accountable leadership.</p><div className="js-thesis-tags">{['Launching a new market?','Spend rising, efficiency falling?','Missing senior ownership?'].map(t=><span className="js-tag" key={t}>{t}</span>)}</div></div></div></section>
 <section className="js-wrap js-section" id="js-services"><div className="js-section-head"><div><div className="js-eyebrow">02 / How I help</div><h2>The right expertise.<br/><span className="js-serif">The right level of involvement.</span></h2></div><p className="js-side-note">From an independent diagnostic to embedded leadership. Built around what your business actually needs.</p></div><div className="js-services"><div className="js-service-tabs" role="tablist" aria-label="Engagement options">{services.map((s,i)=><button key={s.name} id={'service-tab-'+i} role="tab" aria-selected={service===i} tabIndex={service===i?0:-1} onKeyDown={(event)=>navigateTab(event,i)} aria-controls="service-panel" className={'js-service-tab '+(service===i?'active':'')} onClick={()=>setService(i)}><span className="num">0{i+1}</span><span className="label">{s.name}<small>{s.label}</small></span><ArrowUpRight size={17}/></button>)}</div><div className="js-service-panel js-reveal" key={service} role="tabpanel" id="service-panel" tabIndex={0} aria-labelledby={'service-tab-'+service}><div className="js-eyebrow" style={{color:ORANGE}}>{active.tag}</div><h3>{active.intro}</h3><p>{active.text}</p><div className="js-service-points">{active.points.map(p=><div className="js-service-point" key={p}><Check size={14}/><span>{p}</span></div>)}</div><p style={{fontSize:12}}>{active.fit}</p><p className="js-service-timing">{active.timing}</p><button className="js-primary" style={{marginTop:24}} onClick={()=>go('contact')}>Explore this engagement <ArrowUpRight size={16}/></button></div></div></section>
 <section className="js-ai" id="js-ai"><div className="js-wrap js-ai-layout"><div><div className="js-eyebrow"><span className="js-dot"/>03 / AI-enabled growth operations</div><h2>Less busywork.<br/>Better decisions.<br/><span className="js-serif">Practical AI.</span></h2><p>Not another tool looking for a problem. I design and build internal workflows, dashboards and assistants around the decisions your team needs to make.</p><p style={{marginTop:17}}>Reporting. Performance monitoring. Research. Project workflows. More time understanding what matters, less time collecting it.</p><button className="js-textlink" onClick={()=>{setService(4);go('services')}}>Explore the operations audit <ArrowUpRight size={17}/></button></div><div><div className="js-workflow"><div className="js-eyebrow" style={{color:'#BFC3B6'}}>The operating principle</div>{[['Start with the workflow','Find where time is lost and decisions slow down.'],['Build the smallest useful system','Test a credible solution before scaling it.'],['Keep people accountable','Human judgment stays in commercially important decisions.'],['Measure what improves','Time saved. Fewer errors. Faster, better decisions.']].map(([title,text],i)=><div className="js-workflow-row" key={title}><span className="js-workflow-num">0{i+1}</span><div><h3>{title}</h3><p>{text}</p></div></div>)}</div><div className="js-workflow-footer">BUILD, BUY OR LEAVE ALONE. VALUE DECIDES.</div></div></div></section>
 <section className="js-wrap js-section"><div className="js-section-head"><div><div className="js-eyebrow">04 / The approach</div><h2>Clarity first.<br/><span className="js-serif">Then momentum.</span></h2></div><p className="js-side-note">A practical engagement that leaves your people, processes and decisions stronger.</p></div><div className="js-process">{[['Diagnose','Understand your objectives, customer economics and constraints.'],['Prioritise','Turn the highest-value decisions into a focused operating plan.'],['Embed','Work with your team and agencies to drive accountable execution.'],['Improve','Build a repeatable cadence for analysis, testing and investment.'],['Build lasting capability','Strengthen the systems and people. Avoid permanent dependency.']].map(([title,text],i)=><div className="js-step" key={title}><span>0{i+1}</span><h3>{title}</h3><p>{text}</p></div>)}</div></section>
 <section className="js-wrap js-section" id="js-about"><div className="js-about"><div className="js-profile"><div className="js-eyebrow">Independent leadership.<br/>Global perspective.</div><div className="js-profile-mark" aria-hidden="true">js.</div><div className="js-profile-bottom"><span>JANDRÉ SCHOLTZ<br/>CAPE TOWN, SOUTH AFRICA</span><Globe size={22} strokeWidth={1}/></div></div><div className="js-about-copy"><div className="js-eyebrow">05 / The person behind the work</div><h2>Commercial thinking.<br/><span className="js-serif">Builder’s instinct.</span></h2><p>I’m Jandré, a growth and performance marketing leader based in Cape Town, working with digital businesses across global markets.</p><p>Over 7+ years, I’ve worked across apps, fintech, SaaS, e-commerce, telecommunications and subscriptions, from hands-on channel execution to leading teams and growth functions.</p><p>My MCom in Corporate Finance shapes how I think about customer economics and the quality of growth. My experience building campaigns, teams and internal AI systems keeps that thinking grounded in what actually works.</p><a className="js-textlink" href={LINKEDIN} target="_blank" rel="noopener noreferrer">More about my experience <ArrowUpRight size={16}/></a><div className="js-principles">{['Evidence before opinion','Focus before activity','Capability before dependency'].map(p=><span key={p} className="js-tag">{p}</span>)}</div></div></div></section>
 <section className="js-wrap js-section"><div className="js-faq-layout"><div><div className="js-eyebrow">06 / A few useful answers</div><h2>Before we<br/><span className="js-serif">start talking.</span></h2></div><div>{faqs.map(([q,a],i)=><div className="js-faq-item" key={q}><button className="js-faq-q" id={'faq-q-'+i} aria-expanded={faq===i} aria-controls={'faq-a-'+i} onClick={()=>setFaq(faq===i?null:i)}>{q}{faq===i?<Minus size={17}/>:<Plus size={17}/>}</button><div hidden={faq!==i} id={'faq-a-'+i} role="region" aria-labelledby={'faq-q-'+i} className="js-faq-answer">{a}</div></div>)}</div></div></section>
 <section className="js-cta" id="js-contact"><div className="js-wrap js-cta-layout"><div><div className="js-eyebrow">Your next stage of growth starts with a conversation.</div><h2>What’s holding<br/>your growth back?</h2><p>Let’s talk about your current situation, the decisions ahead and whether I’m the right person to help.</p></div><div><a className="js-cta-button" href={LINKEDIN} target="_blank" rel="noopener noreferrer">Let’s connect on LinkedIn <ArrowUpRight size={22}/></a><p className="js-cta-note">No generic sales presentation. Your business first.</p></div></div></section>
 </main><footer className="js-wrap js-footer"><span className="js-wordmark" style={{fontSize:16}}>Jandré Scholtz<span style={{color:ORANGE}}>.</span></span><p>Fractional growth leadership · Cape Town / Global</p><button className="js-textlink" onClick={()=>go('top')}>Back to top ↑</button></footer></div>
}
